### ISSUE TITLE
Handwriting database images cause errors

### ISSUE THREAD

**Issue by ex-tag** [CSAFE-ISU/handwriter#114]
**Describe the bug**
Handwriting database images cause CSAFE-ISU Handwriter to error
```
Unusual amounts of interconnected paths being detected. Do you have crossed out writing in your document?
Error in letterPaths(allPaths, skel_graph0, preStackBreaks) : 
  object 'dists' not found
``` 

**To Reproduce**
1. CSAFE-ISU offers a database of handwriting images:
https://data.csafe.iastate.edu/HandwritingDatabase/#
(Click on "Download All Handwriting Images")
2. This image database can be used to train the CSAFE-ISU Handwriter:
a.  Download the zipped image files.
b. Unzip the image files.
c. Copy the images files to the folder "main_dir/data/template_docs".
d. When in R, train the CSAFE-ISU Handwriter from the image templates
`library('handwriter');
template <- make_clustering_templates(
     template_dir = "/main_dir",
     template_images_dir = "/main_dir/data/template_docs",
     writer_indices = c(7,10),
     max_edges = 25,
     centers_seed = 100,
     graphs_seed = 101,
     K = 40,
     num_dist_cores = 4,
     max_iters = 25);
`.
3. The database can not be trained on without throwing an error
`
Unusual amounts of interconnected paths being detected. Do you have crossed out writing in your document?
Error in letterPaths(allPaths, skel_graph0, preStackBreaks) : 
  object 'dists' not found
`

**Expected behavior**
Both solutions would be the expected behavior:
1. For the program to skip the image files which it cannot process, and then report those files to the user after the program has trained. To stop on each and every file, is inefficient for the user who must manually remove or correct each breaking file.
2. For the program to ignore crossed-out writing, but still process the remaining writing in the image files.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac OS
 - Version [e.g. 22] - 14.3

**Comment by stephaniereinders** [comment]
I started digging into the problem.

## Error location in code
Here are the function calls:
`make_clustering_templates()` > `process_batch_dir()` > `process_batch_list()` > `processDocument()` > `processHandwriting()` > `letterPaths()`. 

The function `letterPaths()` returns the error 

> "Unusual amounts of interconnected paths being detected. Do you have crossed out writing in your document?" in the following code block:

```
tryCatch(
    expr = {
      dists <- distances(nodeGraph0, v = names(V(nodeGraph0)), to = names(V(nodeGraph0)), weights = E(nodeGraph0)$nodeOnlyDist)
    }, error = function(e) {
      message("Unusual amounts of interconnected paths being detected. Do you have crossed out writing in your document?")
    }
  )
```

## Testing
Using the Rstudio debugger, I called `processDocument()` on the CSAFE Handwriting Database file "w0001_s01_pLND_r02.png". I ran the line of code 
```
dists <- distances(nodeGraph0, v = names(V(nodeGraph0)), to = names(V(nodeGraph0)), weights = E(nodeGraph0)$nodeOnlyDist)
```
outside of the Try-Catch function and it returned the error 

> Error: vector memory exhausted (limit reached?)

The test document "w0001_s01_pLND_r02.png" does not have crossed-out writing so handwriter should be able to process it as is.

`sessionInfo()` returns the following for my computer: 
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.4

## Next Steps
- Check memory requirements from OMNI on speed tests
