### ISSUE TITLE
Limit displayed image sizes on shiny app

### ISSUE THREAD

**Issue by Jamesetay1** [CSAFE-ISU/handwriter#12]
Right now, images will show in their true size, even if its larger than the size of the shiny window.
Instead, there should be a limit put in place on the UI elements so that images are scaled down when viewing.  

This could have some weird interaction when cropping that should be taken into account

**Comment by stephaniereinders** [comment]
I figured out how rotate and crop an image scaled to fit the window in a separate, simplified shiny app:  https://github.com/stephaniereinders/Shiny_crop_and_rotate.

**Comment by stephaniereinders** [comment]
Shiny app has been moved to its own repo.
