### ISSUE TITLE
Subscript out of bounds

### ISSUE THREAD

**Issue by ex-tag** [CSAFE-ISU/handwriter#127]
**Describe the bug**
```R
Processing document w0665_s03_pWOZ_r03.png...
path in readPNGBinary: /main_dir/data/template_docs/w0665_s03_pWOZ_r03.png
Starting Processing...
Getting Nodes...and merging them...
Finding direct paths...and loops...
Looking for graph break points...and discarding bad ones...
Isolating graph paths...
Organizing letters...
Creating letter lists...
Adding character features...
Document processing complete.

Saving processed document w0665_s03_pWOZ_r03.png...

Error in strsplit(docname, " ")[[1]] : subscript out of bounds
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**To Reproduce**

1. CSAFE-ISU offers a database of handwriting images:
https://data.csafe.iastate.edu/HandwritingDatabase/#
(Click on "Download All Handwriting Images")
2. This image database can be used to train the CSAFE-ISU Handwriter:
a. Download the zipped image files.
b. Unzip the image files.
c. Copy the image file "w0665_s03_pWOZ_r03.png" to the folder "main_dir/data/template_docs".
d. When in R, train the CSAFE-ISU Handwriter from the image templates
```R
library('handwriter');

template <- make_clustering_templates(
     template_dir = "/main_dir",
     template_images_dir = "/main_dir/data/template_docs",
     writer_indices = c(7,10),
     max_edges = 25,
     centers_seed = 100,
     graphs_seed = 101,
     K = 40,
     num_dist_cores = 4,
     max_iters = 25);
```

**Expected behavior**
For the image file to be processed.

**Desktop (please complete the following information):**
```R
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.3
```

**Comment by stephaniereinders** [comment]
I couldn't reproduce the error: handwriter successfully processed the document and continued on to the next steps on `make_clustering_templates()`. But I think "Error in strsplit(docname, " ")[[1]] : subscript out of bounds" might have occurred in the above instance because `make_clustering_templates()` calls `process_batch_dir()` to attempt to process each doc in template_images_dir. After trying to process each doc, `process_batch_dir()` reads each line of problems.txt to extract the docname of problem documents. However, strsplit(docname, " ")[[1]] returns an error if docname wasn't found in the line of text. I'll add an if statement to check whether the docname was found before trying to extract it.

**Comment by stephaniereinders** [comment]
I was able to reproduce the error by typing "NULL anvoiaejrio avoimaeifr moanvo iajeri adm okaeor mo" in problems.txt  and running 

```
template <- make_clustering_templates(
  template_dir = "/Volumes/T7_Shield/CSAFE/handwriting_datasets/test_template",
  template_images_dir = "/Volumes/T7_Shield/CSAFE/handwriting_datasets/test_template/data/template_docs",
  writer_indices = c(2,5),
  max_edges = 25,
  centers_seed = 100,
  graphs_seed = 101,
  K = 40,
  num_dist_cores = 4,
  max_iters = 25)
```
Output:
> Processing template training documents...
Listing documents to be processed...
Error in strsplit(docname, " ")[[1]] : subscript out of bounds

**Comment by stephaniereinders** [comment]
#130 fixed error but not the warning messages
