### ISSUE TITLE
Vector Memory Exhausted and Warning Messages

### ISSUE THREAD

**Issue by ex-tag** [CSAFE-ISU/handwriter#129]
**Describe the bug**
```R
The following documents could not be processed: 
Loading processed template training documents...
Error: vector memory exhausted (limit reached?)
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  At least 1 of the nodes in the potential loops has more than 2 neighbors after removal of the connections. Try again! 
The nodes in question are: 

2: In create_letter_lists(allPaths, letters, nodeList, nodeConnections,  :
  Maybe a loop that didn't merge with node. letterList[[47]]
3: In create_letter_lists(allPaths, letters, nodeList, nodeConnections,  :
  Maybe a loop that didn't merge with node. letterList[[47]]
4: In doTryCatch(return(expr), name, parentenv, handler) :
  At least 1 of the nodes in the potential loops has more than 2 neighbors after removal of the connections. Try again! 
The nodes in question are: 

5: In doTryCatch(return(expr), name, parentenv, handler) :
  At least 1 of the nodes in the potential loops has more than 2 neighbors after removal of the connections. Try again! 
The nodes in question are: 

6: In doTryCatch(return(expr), name, parentenv, handler) :
  At least 1 of the nodes in the potential loops has more than 2 neighbors after removal of the connections. Try again! 
The nodes in question are: 

7: In create_letter_lists(allPaths, letters, nodeList, nodeConnections,  :
  Maybe a loop that didn't merge with node. letterList[[267]]
8: In create_letter_lists(allPaths, letters, nodeList, nodeConnections,  :
  Maybe a loop that didn't merge with node. letterList[[267]]
9: In doTryCatch(return(expr), name, parentenv, handler) :
  At least 1 of the nodes in the potential loops has more than 2 neighbors after removal of the connections. Try again! 
The nodes in question are: 
```

**To Reproduce**
1. CSAFE-ISU offers a database of handwriting images:
https://data.csafe.iastate.edu/HandwritingDatabase/#
(Click on "Download All Handwriting Images")
2. This image database can be used to train the CSAFE-ISU Handwriter:
a. Download the zipped image files.
b. Unzip the image files.
c. Copy just the first 600 images to the folder "main_dir/data/template_docs".
d. When in R, train the CSAFE-ISU Handwriter from the image templates with the following command
```R
library('handwriter');

template <- make_clustering_templates(
     template_dir = "/main_dir",
     template_images_dir = "/main_dir/data/template_docs",
     writer_indices = c(7,10),
     max_edges = 25,
     centers_seed = 100,
     graphs_seed = 101,
     K = 40,
     num_dist_cores = 4,
     max_iters = 25);
```  

**Expected behavior**
For the software to gracefully exit without throwing errors or warnings.

**Desktop (please complete the following information):**
```R
> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.3
```

**Comment by stephaniereinders** [comment]
Best practice is to call `make_clustering_templates()` on 100 paragraph-length training documents. More than this becomes computationally infeasible. I will add a statement about this to the README and cause `make_clustering_templates()` to stop if the user tries to use more than 100 training docs. 

**To Do**
- [ ]  Add a statement to the README that best practice is to use 100 training documents for cluster template creation
- [ ]  Update `make_clustering_templates()` to stop if template_images_dir contains more than 100 documents

**Comment by stephaniereinders** [comment]
I think you are confusing two different steps in handwriter's writership analysis process. The steps of the process are the following:

1. Create a clustering template to create a list of common shapes that appear in handwriting.
2. Fit a statistical model to handwriting samples collected from a closed-set of persons of interest.
3. Use the statistical model from STEP 2 to calculate the posterior probability that each person in the closed-set of persons of interest wrote a questioned document.

The algorithm that handwriter uses does not run in polynomial time, so if you try to train on too many documents, it becomes computationally infeasible. Former CSAFE graduate student Amy Crawford found that handwriter gets reasonable accuracy by training clustering templates on 100 training documents and creating 40 clusters. See the published results in https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/sam.11488 for more information. Trying to create a cluster template on 8000 documents is overkill.

However, you can use any of the 8000+ handwriting samples from the CSAFE Handwriting Database as either training documents for the statistical model (STEP 2) or as test documents for STEP 3.
