### ISSUE TITLE
Enable use of shiny app on reiss & locard

### ISSUE THREAD

**Issue by Jamesetay1** [CSAFE-ISU/handwriter#13]
Currently, shiny apps will not run on the server because shiny cannot be installed.  It is being stopped by the installation of package 'httpuv' which shiny depends on.  I contacted CSSM IT but did not hear back from that in regards to getting help installing it.

**Comment by stephaniereinders** [comment]
After we fix the bugs, CSAFE users will be able to use handwriter through the Shiny app on https://csafe.shinyapps.io/handwriter/ they won't need to run the app on Reiss or Locard. I'm closing this issue as "not planned."
