### ISSUE TITLE
Continue to improve word separation

### ISSUE THREAD

**Issue by Jamesetay1** [CSAFE-ISU/handwriter#14]
## Basics
There is still some room for improvement for word separation in handwriter.  Ali is using this feature quite a bit so if you want to ask for more sample data on where things fail she would be a good one to ask.

I created this document detailing everything:
[Word Separation in handwriter (3).pdf](https://github.com/CSAFE-ISU/handwriter/files/9577920/Word.Separation.in.handwriter.3.pdf)

**Comment by stephaniereinders** [comment]
Here are 9 example of the common phrase, "The early bird may get the worm, but the second mouse gets the cheese," written by CSAFE writer 1. Ally looked at whether each of the words "the" was separated correctly when handwriter processed the writing. In the table below, "y" means the word was separated correctly and "n" means the word was not separated correctly.

| Doc                | First The         | Second The  | Third The       |
| ------------- | ------------- | ------------- | ------------- |
| w0001_s01_pPHR_r01  | n | y | y |
| w0001_s01_pPHR_r02  | y | y | y |
| w0001_s01_pPHR_r03  | y | y | y |
| w0001_s02_pPHR_r01  | n | y | y |
| w0001_s02_pPHR_r02  | n | n | y |
| w0001_s02_pPHR_r03  | n | n | n |
| w0001_s03_pPHR_r01  | y | y | y |
| w0001_s03_pPHR_r02  | n | y | y |
| w0001_s03_pPHR_r01  | n | n | y |

![w0001_s01_pPHR_r01](https://user-images.githubusercontent.com/30669200/197264900-f96555ec-0829-45a0-8739-b0f8ab796154.png)
![w0001_s01_pPHR_r02](https://user-images.githubusercontent.com/30669200/197265008-08b1baa6-95e9-47f4-aad6-617c954823c6.png)
![w0001_s01_pPHR_r03](https://user-images.githubusercontent.com/30669200/197265045-9296f293-d721-44ec-a90c-1cc97ff5ab6f.png)
![w0001_s02_pPHR_r01](https://user-images.githubusercontent.com/30669200/197265105-986f55f1-ea47-4942-a481-1e5ce2c3d2f5.png)
![w0001_s02_pPHR_r02](https://user-images.githubusercontent.com/30669200/197265119-e7e70ff4-a994-44fe-9a51-e5eed7e22f6e.png)
![w0001_s02_pPHR_r03](https://user-images.githubusercontent.com/30669200/197265146-dc628d2c-9d01-4923-ac81-01f0b7c9024c.png)
![w0001_s03_pPHR_r01](https://user-images.githubusercontent.com/30669200/197265183-369814d5-b9f5-4c3a-87e5-9e477f1cc62b.png)
![w0001_s03_pPHR_r02](https://user-images.githubusercontent.com/30669200/197265185-1aac1069-24ce-49a9-ab20-f43dfcaf1bb9.png)
![w0001_s03_pPHR_r03](https://user-images.githubusercontent.com/30669200/197265186-ee09e4e7-8521-478b-810f-8bbcfefd0018.png)

**Comment by stephaniereinders** [comment]
@erichare at OMNI Analytics built Python functions to separate documents into words in 85e07ac1341cb3c725ab549c53d2d3dfc5788d79. Thanks @erichare! 

The new word separation process splits a document into words and saves each word as its own image. Then handwriter can be used to process the word images. I think this means that we can remove the old word separation process that happens automatically as part of the graph extraction process, but I am not sure. I made a separate issue to look into this.
