### ISSUE TITLE
Incorporate the styler package with pre-commit

### ISSUE THREAD

**Issue by stephaniereinders** [CSAFE-ISU/handwriter#24]
https://github.com/lorenzwalthert/precommit

**Comment by ahgamut** [comment]
The [`pre-commit`](https://github.com/lorenzwalthert/precommit) R package mentioned in the above link uses Python in the background to do a bunch of things automatically whenever you do a `git commit`:

* style your code using the `styler` package
* lint your code using the `lintr` package (point out potential bugs/inconsistencies)
* render vignettes
* check your package has all dependencies listed out properly, etc.

`pre-commit` requires a simple `yml` configuration file, and it requires `python` to be installed on your computer.

I tried it out here: https://github.com/ahgamut/handwriter/commits/rearrange

The advantage of `pre-commit` is that it automatically enforces a consistent style and structure on the code in an R package.

One of the disadvantages is that if you introduce `pre-commit` after a while, it can [add a lot of changes at once](https://github.com/ahgamut/handwriter/commit/9771b225ad3c8066195e296dec51488d90471ff3), which messes with `git blame` and the update history of the code.

Perhaps a `pre-commit` can be attempted after other updates to `handwriter`.
