### ISSUE TITLE
Problem whit the install

### ISSUE THREAD

**Issue by Mariodocumentologia** [CSAFE-ISU/handwriter#6]
Dear James: I am typeing to you from Argentina. I am very interested in using handwired master, but I have a problem with the install. I attach picture. I request your help please. Thanks a lot

![20200529_033626](https://user-images.githubusercontent.com/66111157/83235412-3967dc00-a168-11ea-838a-0140f223ba70.jpg)

**Comment by Jamesetay1** [comment]
@Mariodocumentologia Hello, sorry it took so long to respond.  I had forgotten a few steps in my instructions - please try this slightly modified set of instructions: [https://csafe-isu.github.io/handwriter/howto](https://csafe-isu.github.io/handwriter/howto). In this case, I forgot to include `install.packages("devtools")` in the instructions. Let me know if there are any more issues and I'll be quicker to respond!

**Comment by Jamesetay1** [comment]
Tagging @stephaniereinders to make sure you see this :)
